// <auto-generated />
using System;
using Geographic_Icons_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Geographic_Icons_API.Migrations
{
    [DbContext(typeof(GeographicIconsContext))]
    partial class GeographicIconsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Geographic_Icons_API.CityCountry", b =>
                {
                    b.Property<int>("CityCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityCountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CityCountryPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ContinentId")
                        .HasColumnType("int");

                    b.Property<int?>("GeographicIconId")
                        .HasColumnType("int");

                    b.Property<decimal>("Population")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("TotalLandArea")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("CityCountryId");

                    b.HasIndex("ContinentId");

                    b.HasIndex("GeographicIconId");

                    b.ToTable("CitiesCountries");
                });

            modelBuilder.Entity("Geographic_Icons_API.Continent", b =>
                {
                    b.Property<int>("ContinentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContinentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ContinentPicture")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ContinentId");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("Geographic_Icons_API.GeographicIcon", b =>
                {
                    b.Property<int>("GeographicIconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FinishingDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("GeographicIconPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeographicIconId");

                    b.ToTable("GeographicIcons");
                });

            modelBuilder.Entity("Geographic_Icons_API.CityCountry", b =>
                {
                    b.HasOne("Geographic_Icons_API.Continent", "Continent")
                        .WithMany("Cities_Countries")
                        .HasForeignKey("ContinentId");

                    b.HasOne("Geographic_Icons_API.GeographicIcon", "GeographicIcon")
                        .WithMany("CitiesCountries")
                        .HasForeignKey("GeographicIconId");
                });
#pragma warning restore 612, 618
        }
    }
}
